import base64

class ReportGenerator:
    @staticmethod
    def generate_html_report(run_data, session_name="NUC-SIM-LOG"):
        """
        Generates a styled HTML report from the simulation run data.
        """
        history = run_data.get('history', [])
        meta = run_data.get('telemetry', {})
        
        # Calculate stats
        max_pwr = 0
        max_temp = 0
        duration = 0
        if history:
            max_pwr = max([h['power'] for h in history])
            max_temp = max([h['temp'] for h in history])
            duration = history[-1]['time']
            
        html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: sans-serif; padding: 40px; color: #333; }}
                h1 {{ color: #e67e22; border-bottom: 2px solid #e67e22; padding-bottom: 10px; }}
                .stat-box {{ background: #f4f4f4; padding: 20px; margin: 10px 0; border-radius: 5px; }}
                .alert {{ color: red; font-weight: bold; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #eee; }}
            </style>
        </head>
        <body>
            <h1>NUCLEAR SIMULATOR REPORT</h1>
            <h3>Session ID: {session_name}</h3>
            
            <div class="stat-box">
                <b>Max Power:</b> {max_pwr:.1f} MW<br>
                <b>Max Core Temp:</b> {max_temp:.1f} °C<br>
                <b>Duration:</b> {duration:.0f} seconds<br>
                <b>Final Status:</b> {"SCRAMMED" if meta.get('scram') else "OPERATIONAL"}
            </div>
            
            <h3>Event Context</h3>
            <p>This report was generated from a non-operational educational simulation. 
            All values are normalized approximations.</p>
            
            <h3>Telemetry Log (Sampled)</h3>
            <table>
                <tr>
                    <th>Time (s)</th>
                    <th>Power (MW)</th>
                    <th>Temp (°C)</th>
                    <th>Reactivity (pcm)</th>
                </tr>
        """
        
        # Add rows (decimated)
        for i, entry in enumerate(history):
            if i % 5 == 0: # Every 5th entry to save space
                html += f"""
                <tr>
                    <td>{entry['time']:.1f}</td>
                    <td>{entry['power']:.1f}</td>
                    <td>{entry['temp']:.1f}</td>
                    <td>{entry['reactivity']:.0f}</td>
                </tr>
                """
                
        html += """
            </table>
            <div style="margin-top: 50px; font-size: 0.8em; color: #999;">
                Generated by Nuclear Reactor Systems Simulator v1.0
            </div>
        </body>
        </html>
        """
        
        return html
